#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Symbol.XamarinEMDK.SAMSample1.Resource", IsApplication=true)]

namespace Symbol.XamarinEMDK.SAMSample1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int btnGetSAMInfo = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int txtAutoDetectText = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int txtStatus = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int get_sam_info = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int message_connect_error = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int message_disconnecting = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int message_failed_to_get_sams = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int message_nfc_not_supported = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int message_sam_connected_successfully = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int message_sam_exception_enumerate = 2130968582;
			
			// aapt resource value: 0x7f04000f
			public const int message_tag_compatible = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int message_tag_detected = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int message_tag_not_compatible = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int message_transceive = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int message_transceive_failed = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int place_card_message = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int status = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int version = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int version_error = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
