#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Symbol.XamarinEMDK.BarcodeSample1.Resource", IsApplication=true)]

namespace Symbol.XamarinEMDK.BarcodeSample1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int triggers_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int buttonStartScan = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int buttonStopScan = 2131099669;
			
			// aapt resource value: 0x7f06000f
			public const int checkBoxCode128 = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int checkBoxCode39 = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int checkBoxContinuous = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int checkBoxEAN13 = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int checkBoxEAN8 = 2131099659;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout1 = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int scrollView1 = 2131099673;
			
			// aapt resource value: 0x7f060004
			public const int spinnerScanners = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int spinnerTriggers = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int tableLayout2 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int tableLayout3 = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int tableRow1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int tableRow3 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow4 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow5 = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int tableRow7 = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int tableRow9 = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int textView16 = 2131099664;
			
			// aapt resource value: 0x7f060018
			public const int textView26 = 2131099672;
			
			// aapt resource value: 0x7f060008
			public const int textView6 = 2131099656;
			
			// aapt resource value: 0x7f06001b
			public const int textViewData = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int textViewStatus = 2131099671;
			
			// aapt resource value: 0x7f060003
			public const int textViewlblScanner = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int textViewlblTrigger = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int scanner_prompt = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int trigger_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
