#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Symbol.XamarinEMDK.SimulScanSample1.Resource", IsApplication=true)]

namespace Symbol.XamarinEMDK.SimulScanSample1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int pref_template_entries = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int pref_template_values = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000d
			public const int button4 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int button5 = 2131296270;
			
			// aapt resource value: 0x7f090013
			public const int content = 2131296275;
			
			// aapt resource value: 0x7f090000
			public const int device_controls = 2131296256;
			
			// aapt resource value: 0x7f090009
			public const int doccapImage = 2131296265;
			
			// aapt resource value: 0x7f090015
			public const int regionAbsConf = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int regionData = 2131296276;
			
			// aapt resource value: 0x7f090012
			public const int regionImage = 2131296274;
			
			// aapt resource value: 0x7f09000a
			public const int regionLV = 2131296266;
			
			// aapt resource value: 0x7f090010
			public const int regionName = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int regionProcessingMode = 2131296273;
			
			// aapt resource value: 0x7f090016
			public const int regionRelConf = 2131296278;
			
			// aapt resource value: 0x7f090002
			public const int resultsLayout = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int settings = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int spinner2 = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int textView1 = 2131296267;
			
			// aapt resource value: 0x7f09000f
			public const int titleBar = 2131296271;
			
			// aapt resource value: 0x7f090006
			public const int tvOCRTimeMs = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int tvParseTook = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int tvProcTook = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int tvSegmentTimeMs = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int tvTime = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int tvTimestamp = 2131296264;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main_2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int region_item = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int action_settings = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hello_world = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int parsing_took = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int pref_key = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int pref_template_default = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int processing_took = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int time = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
